/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import dashbikash.spark.etl.SparkETLApp;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SparkETLApp classUnderTest = new SparkETLApp();
        assertTrue(true);
    }
}
